version: '3'
services:
    servo_node:
        build: ./ServoNodeDocker
        container_name: servo_node
        restart: always
        network_mode: host
        devices:
            - "/dev/i2c-1"
        command: ros2 rosrun servo_node ServoNode
