FROM ros:foxy-ros-base

RUN apt update && \
	apt upgrade -y

RUN rm -rf /var/lib/apt/lists/

RUN mkdir -p ~/ros2_ws/src/ && \
	cd ~/ros2_ws/src/ && \
	git clone --recursive https://github.com/CatixBot/ServoNode.git
